import fs from 'fs';
import zlib from 'zlib';
import { pipeline } from 'stream/promises';
import { createVoxelStream, resolveOutputDtype, describeDtype } from '../utils/volumeStream.js';

export async function convertToNrrd(volume, outputPath) {
    console.log('Converting DICOM to NRRD...');

    const { dimensions, spacing, origin } = volume;
    const { rows, columns, depth } = dimensions;

    const dtype = resolveOutputDtype(volume);
    console.log('NRRD data type:', describeDtype(volume, dtype));

    const header = [
        'NRRD0004',
        '# Complete NRRD file generated by dicom-processor',
        `type: ${dtype === 'int16' ? 'short' : 'float'}`,
        'dimension: 3',
        'space: right-anterior-superior',
        `sizes: ${columns} ${rows} ${depth}`,
        `space directions: (${spacing[0]},0,0) (0,${spacing[1]},0) (0,0,${spacing[2]})`,
        'kinds: domain domain domain',
        // Still describes the data once decompressed - gzip does not change the byte order.
        'endian: little',
        'encoding: gzip',
        `space origin: (${origin[0]},${origin[1]},${origin[2]})`,
        '',
        ''
    ].join('\n');

    // Only the data section is compressed; the header stays plain text, which is what makes a NRRD
    // still readable with `head`.
    fs.writeFileSync(outputPath, header);
    await pipeline(
        createVoxelStream(volume, dtype),
        zlib.createGzip({ level: 6 }),
        fs.createWriteStream(outputPath, { flags: 'a' })
    );

    console.log('Successfully wrote NRRD file:', outputPath);
    return outputPath;
}
