import fs from 'fs';

export async function convertToNrrd(volume, outputPath) {
    console.log('Converting DICOM to NRRD...');

    const { volumeData, dimensions, spacing, origin } = volume;
    const { rows, columns, depth } = dimensions;

    const header = [
        'NRRD0004',
        '# Complete NRRD file generated by dicom-processor',
        'type: float',
        'dimension: 3',
        'space: right-anterior-superior',
        `sizes: ${columns} ${rows} ${depth}`,
        `space directions: (${spacing[0]},0,0) (0,${spacing[1]},0) (0,0,${spacing[2]})`,
        'kinds: domain domain domain',
        'endian: little',
        'encoding: raw',
        `space origin: (${origin[0]},${origin[1]},${origin[2]})`,
        '',
        ''
    ].join('\n');

    fs.writeFileSync(outputPath, header);
    fs.appendFileSync(outputPath, Buffer.from(volumeData.buffer));

    console.log('Successfully wrote NRRD file:', outputPath);
    return outputPath;
}
